(()=>{'use strict';
const VEHICLES=new Set(['car','truck','bus','motorcycle']),HEAVY=new Set(['truck','bus']);
const LABEL={car:'Light Vehicle',truck:'Truck / Truck & Dog',bus:'Bus',motorcycle:'Motorcycle'};
const $=id=>document.getElementById(id),video=$('video'),canvas=$('overlay'),ctx=canvas.getContext('2d');
let model=null,stream=null,running=false,detecting=false,lastDetect=0,tracks=new Map(),nextId=1,wakeLock=null,calMode=null,tapPts=[];
let detCount=0,detWindow=performance.now(),suppressed=0,lastDets=[],eventFingerprints=[],lostBank=[];
const defaults={inside:0,inTotal:0,outTotal:0,events:[],line:null,waiting:null,reverse:false,profile:'site',modelMode:'fast',dogGuard:true,setupLocked:false,paused:false};
let state=load();
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem('siteGateTracker')||'{}'))}catch{return {...defaults}}}
function save(){localStorage.setItem('siteGateTracker',JSON.stringify(state));render()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){
 $('inside').textContent=state.inside;$('inTotal').textContent=state.inTotal;$('outTotal').textContent=state.outTotal;
 $('reverse').textContent='DIRECTION: '+(state.reverse?'REVERSED':'NORMAL');
 $('profile').textContent='PROFILE: '+({site:'SITE HEAVY',mixed:'MIXED',strict:'STRICT'}[state.profile]||'SITE HEAVY');
 $('modelMode').textContent='MODEL: '+state.modelMode.toUpperCase();$('dogGuard').textContent='DOG GUARD: '+(state.dogGuard?'ON':'OFF');
 $('lockSetup').textContent='SETUP: '+(state.setupLocked?'LOCKED':'UNLOCKED');$('pause').textContent='COUNTING: '+(state.paused?'PAUSED':'LIVE');
 const e=$('events');e.innerHTML=state.events.length?'':'<div class="small" style="padding:12px;text-align:center">No movements yet</div>';
 state.events.slice(0,12).forEach(x=>{const d=document.createElement('div');d.className='event';d.innerHTML=`<span>${esc(x.time)}</span><span>${esc(x.type)}</span><b>${esc(x.dir)}</b><span>#${x.inside}</span><span>${esc(x.source||'AI')}</span><span>${esc(x.quality||'')}</span>`;e.appendChild(d)})
}
render();
async function keepAwake(){try{if('wakeLock'in navigator)wakeLock=await navigator.wakeLock.request('screen')}catch{}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&running)keepAwake()});
async function loadModel(){model=null;$('status').textContent='Loading '+state.modelMode+' model…';await tf.setBackend('webgl');await tf.ready();model=await cocoSsd.load({base:state.modelMode==='fast'?'lite_mobilenet_v2':'mobilenet_v2'});$('status').textContent='Tracking'}
async function start(){if(running)return;$('start').disabled=true;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:false});video.srcObject=stream;await video.play();await new Promise(r=>video.readyState>=2?r():video.onloadedmetadata=r);resize();running=true;keepAwake();await loadModel();$('start').textContent='CAMERA RUNNING';$('hint').textContent=state.line?'Tracking gate corridor.':'Set gate line with two taps.';loop()}catch(e){console.error(e);$('status').textContent='Camera/model error';$('hint').textContent='Open in Safari over HTTPS and allow Camera.';$('start').disabled=false}}
function resize(){if(video.videoWidth){canvas.width=video.videoWidth;canvas.height=video.videoHeight}}
video.addEventListener('loadedmetadata',resize);window.addEventListener('resize',resize);
function linePx(){return state.line?state.line.map(p=>[p[0]*canvas.width,p[1]*canvas.height]):null}
function signedDist(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1;return(dx*(p[1]-a[1])-dy*(p[0]-a[0]))/len}
function projT(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],den=dx*dx+dy*dy||1;return((p[0]-a[0])*dx+(p[1]-a[1])*dy)/den}
function iou(a,b){const ax2=a[0]+a[2],ay2=a[1]+a[3],bx2=b[0]+b[2],by2=b[1]+b[3],x1=Math.max(a[0],b[0]),y1=Math.max(a[1],b[1]),x2=Math.min(ax2,bx2),y2=Math.min(ay2,by2),inter=Math.max(0,x2-x1)*Math.max(0,y2-y1),u=a[2]*a[3]+b[2]*b[3]-inter;return u?inter/u:0}
function insideRect(p,r){if(!r)return false;const[x1,y1,x2,y2]=r;return p[0]>=Math.min(x1,x2)*canvas.width&&p[0]<=Math.max(x1,x2)*canvas.width&&p[1]>=Math.min(y1,y2)*canvas.height&&p[1]<=Math.max(y1,y2)*canvas.height}
function profile(){if(state.profile==='mixed')return{score:.34,hits:3,sideN:2,band:.019,minNormal:.010,heavyOnly:false,ghostMs:2400,reidMs:4200};if(state.profile==='strict')return{score:.46,hits:5,sideN:3,band:.025,minNormal:.018,heavyOnly:true,ghostMs:3300,reidMs:5200};return{score:.34,hits:4,sideN:2,band:.021,minNormal:.012,heavyOnly:true,ghostMs:2900,reidMs:4800}}
function dominant(v){return Object.entries(v).sort((a,b)=>b[1]-a[1])[0]?.[0]||'truck'}
function makeTrack(d,now,id=nextId++){const[x,y,w,h]=d.bbox,cx=x+w/2,cy=y+h/2;return{id,cx,cy,vx:0,vy:0,bbox:d.bbox,score:d.score,avgScore:d.score,lastSeen:now,firstSeen:now,hits:1,travel:0,votes:{[d.class]:1},label:d.class,history:[[cx,cy,now]],originSide:null,originN:0,inBand:false,farSide:null,farN:0,lastEvent:0,recovered:0}}
function parkLost(t,now){lostBank.push({...t,lostAt:now});lostBank=lostBank.filter(x=>now-x.lostAt<7000).slice(-80)}
function tryReid(d,now){const p=profile(),[x,y,w,h]=d.bbox,cx=x+w/2,cy=y+h/2;let best=null,bestCost=9,idx=-1;lostBank=lostBank.filter(t=>now-t.lostAt<p.reidMs);for(let i=0;i<lostBank.length;i++){const t=lostBank[i],dt=Math.min((now-t.lastSeen)/300,8),px=t.cx+t.vx*dt,py=t.cy+t.vy*dt,dist=Math.hypot(cx-px,cy-py),maxD=Math.max(130,Math.hypot(w,h)*1.45);if(dist>maxD)continue;const classPenalty=(HEAVY.has(d.class)!==HEAVY.has(t.label))?.8:0,cost=dist/maxD+(1-iou(d.bbox,t.bbox))*.28+classPenalty;if(cost<bestCost){best=t;bestCost=cost;idx=i}}if(best){lostBank.splice(idx,1);best.recovered=(best.recovered||0)+1;return best}return null}
function updateTrack(t,d,now){const[x,y,w,h]=d.bbox,cx=x+w/2,cy=y+h/2,ox=t.cx,oy=t.cy,dt=Math.max((now-t.lastSeen)/300,.5);t.vx=.68*t.vx+.32*((cx-ox)/dt);t.vy=.68*t.vy+.32*((cy-oy)/dt);t.travel+=Math.hypot(cx-ox,cy-oy);t.cx=cx;t.cy=cy;t.bbox=d.bbox;t.score=d.score;t.avgScore=(t.avgScore*(t.hits||1)+d.score)/((t.hits||1)+1);t.lastSeen=now;t.hits++;t.votes[d.class]=(t.votes[d.class]||0)+1;t.label=dominant(t.votes);t.history.push([cx,cy,now]);if(t.history.length>10)t.history.shift();d.track=t}
function match(dets,now){const active=[...tracks.values()].filter(t=>now-t.lastSeen<2200),used=new Set(),seenIds=new Set();for(const d of dets){const[x,y,w,h]=d.bbox,cx=x+w/2,cy=y+h/2;let best=null,bestCost=9;for(const t of active){if(used.has(t.id))continue;const dt=Math.min((now-t.lastSeen)/300,5),px=t.cx+t.vx*dt,py=t.cy+t.vy*dt,dist=Math.hypot(cx-px,cy-py),maxD=Math.max(110,Math.hypot(w,h)*1.15);if(dist>maxD)continue;const classPenalty=(HEAVY.has(d.class)!==HEAVY.has(t.label))?.75:0,cost=dist/maxD+(1-iou(d.bbox,t.bbox))*.38+classPenalty;if(cost<bestCost){bestCost=cost;best=t}}if(!best)best=tryReid(d,now);if(!best){best=makeTrack(d,now);tracks.set(best.id,best)}else if(!tracks.has(best.id))tracks.set(best.id,best);used.add(best.id);seenIds.add(best.id);updateTrack(best,d,now)}for(const[id,t]of [...tracks])if(!seenIds.has(id)&&now-t.lastSeen>2300){tracks.delete(id);parkLost(t,now)}}
function qualityFor(t){const p=profile();let q=0;q+=Math.min(35,(t.hits/p.hits)*20);q+=Math.min(30,(t.avgScore||0)*40);q+=Math.min(20,t.travel/(canvas.height*.12||1)*12);q+=t.recovered?5:10;if(q>=76)return['HIGH',Math.round(q)];if(q>=58)return['MED',Math.round(q)];return['REVIEW',Math.round(q)]}
function eventFingerprint(t,dir,now){const ln=linePx();if(!ln)return false;const[a,b]=ln,pos=[t.cx,t.cy],along=projT(pos,a,b),p=profile();eventFingerprints=eventFingerprints.filter(e=>now-e.time<p.ghostMs);const dup=eventFingerprints.find(e=>e.dir===dir&&Math.abs(e.along-along)<.13&&(HEAVY.has(t.label)?e.heavy:true));if(dup){suppressed++;return true}eventFingerprints.push({time:now,dir,along,heavy:HEAVY.has(t.label),id:t.id});return false}
function corridorCheck(t,now){if(state.paused)return;const ln=linePx();if(!ln)return;const p=profile();if(t.hits<p.hits)return;const[a,b]=ln,pos=[t.cx,t.cy],dist=signedDist(pos,a,b),band=Math.max(12,canvas.height*p.band),abs=Math.abs(dist),side=dist>band?1:dist<-band?-1:0,pr=projT(pos,a,b);if(pr<-.12||pr>1.12)return;if(t.originSide===null){if(side){if(t.farSide===side)t.originN++;else{t.farSide=side;t.originN=1}if(t.originN>=p.sideN){t.originSide=side;t.farSide=null;t.originN=0}}return}if(side===t.originSide){t.inBand=false;t.farSide=null;t.farN=0;return}if(side===0){t.inBand=true;return}if(side!==-t.originSide)return;const hist=t.history,old=hist.length>3?hist[hist.length-4]:hist[0],normalMove=Math.abs((t.cx-old[0])*(b[1]-a[1])-(t.cy-old[1])*(b[0]-a[0]))/(Math.hypot(b[0]-a[0],b[1]-a[1])||1),jumped=(old&&Math.sign(signedDist([old[0],old[1]],a,b))===t.originSide&&abs>band);if(!t.inBand&&!jumped)return;if(normalMove<Math.max(2,canvas.height*p.minNormal))return;if(t.farSide===side)t.farN++;else{t.farSide=side;t.farN=1}if(t.farN<p.sideN||now-t.lastEvent<1800)return;let dir=t.originSide===-1?'IN':'OUT';if(state.reverse)dir=dir==='IN'?'OUT':'IN';t.originSide=side;t.inBand=false;t.farSide=null;t.farN=0;t.lastEvent=now;if(state.dogGuard&&HEAVY.has(t.label)&&eventFingerprint(t,dir,now))return;const[q,score]=qualityFor(t);record(LABEL[t.label]||t.label,dir,'AI',t.id,t.avgScore,q,score)}
function record(type,dir,source='AI',track='',score='',quality='',qscore=''){if(dir==='IN'){state.inside++;state.inTotal++}else{state.inside=Math.max(0,state.inside-1);state.outTotal++}const now=new Date();state.events.unshift({time:now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),iso:now.toISOString(),type,dir,inside:state.inside,source,track,confidence:Number(score||0).toFixed(2),quality,qscore});state.events=state.events.slice(0,1200);save();flash(dir,type);navigator.vibrate?.([45,35,45])}
function flash(dir,type){const f=$('flash');f.textContent=dir+' • '+type;f.classList.add('show');clearTimeout(f._t);f._t=setTimeout(()=>f.classList.remove('show'),900)}
async function detect(now){if(!model||detecting||video.readyState<2)return;detecting=true;try{const p=profile(),raw=await model.detect(video,35,p.score),dets=raw.filter(x=>VEHICLES.has(x.class)&&(!p.heavyOnly||HEAVY.has(x.class)));match(dets,now);for(const d of dets)corridorCheck(d.track,now);lastDets=dets;draw(dets);detCount++;const elapsed=now-detWindow;if(elapsed>2500){const hz=detCount*1000/elapsed;$('hz').textContent=hz.toFixed(1);$('active').textContent=tracks.size;$('mature').textContent=[...tracks.values()].filter(t=>t.hits>=p.hits).length;$('supp').textContent=suppressed;$('diag').textContent=hz<1.2?'LOW FPS':hz<2.2?'OK':'GOOD';detCount=0;detWindow=now}}catch(e){console.error(e);$('status').textContent='Detection error'}finally{detecting=false}}
function draw(dets=[]){ctx.clearRect(0,0,canvas.width,canvas.height);const ln=linePx();if(ln){const[a,b]=ln,p=profile(),band=Math.max(12,canvas.height*p.band),dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len;ctx.strokeStyle='#fff';ctx.lineWidth=3;for(const s of[-band,band]){ctx.beginPath();ctx.moveTo(a[0]+nx*s,a[1]+ny*s);ctx.lineTo(b[0]+nx*s,b[1]+ny*s);ctx.stroke()}ctx.fillStyle='#fff';ctx.font=`${Math.max(14,canvas.width/50)}px -apple-system`;ctx.fillText('GATE CORRIDOR',a[0]+6,Math.max(20,a[1]-band-8))}if(state.waiting){const r=state.waiting,pts=[[r[0]*canvas.width,r[1]*canvas.height],[r[2]*canvas.width,r[1]*canvas.height],[r[2]*canvas.width,r[3]*canvas.height],[r[0]*canvas.width,r[3]*canvas.height]];ctx.strokeStyle='#ffd166';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(...pts[0]);pts.slice(1).forEach(p=>ctx.lineTo(...p));ctx.closePath();ctx.stroke()}let waitingIds=new Set();for(const d of dets){const t=d.track,[x,y,w,h]=d.bbox;if(insideRect([t.cx,t.cy],state.waiting))waitingIds.add(t.id);const mature=t.hits>=profile().hits;ctx.strokeStyle=mature?'#55e6ff':'#8391a6';ctx.lineWidth=2;ctx.strokeRect(x,y,w,h);ctx.fillStyle='#000c';ctx.fillRect(x,Math.max(0,y-23),Math.min(w,245),23);ctx.fillStyle='#fff';ctx.font=`${Math.max(12,canvas.width/56)}px -apple-system`;ctx.fillText(`#${t.id} ${LABEL[t.label]||t.label} ${mature?'✓':'…'}`,x+4,Math.max(16,y-6))}$('waiting').textContent=waitingIds.size}
function loop(now=performance.now()){if(!running)return;if(!detecting&&now-lastDetect>60){lastDetect=now;detect(now)}requestAnimationFrame(loop)}
canvas.addEventListener('pointerdown',e=>{if(!calMode)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;tapPts.push([x,y]);if(calMode==='gate'&&tapPts.length===2){state.line=tapPts.map(p=>[p[0]/canvas.width,p[1]/canvas.height]);calMode=null;tapPts=[];tracks.clear();save();$('hint').textContent='Gate corridor saved.'}if(calMode==='wait'&&tapPts.length===2){state.waiting=[tapPts[0][0]/canvas.width,tapPts[0][1]/canvas.height,tapPts[1][0]/canvas.width,tapPts[1][1]/canvas.height];calMode=null;tapPts=[];save();$('hint').textContent='Waiting bay saved.'}});
$('start').onclick=start;
$('gate').onclick=()=>{if(state.setupLocked)return $('hint').textContent='Unlock setup first.';if(!running)return $('hint').textContent='Start camera first.';calMode='gate';tapPts=[];$('hint').textContent='Tap TWO points across the vehicle path.'};
$('waitZone').onclick=()=>{if(state.setupLocked)return $('hint').textContent='Unlock setup first.';if(!running)return $('hint').textContent='Start camera first.';calMode='wait';tapPts=[];$('hint').textContent='Tap TWO opposite corners of waiting bay.'};
$('reverse').onclick=()=>{if(state.setupLocked)return $('hint').textContent='Unlock setup first.';state.reverse=!state.reverse;tracks.clear();save()};
$('profile').onclick=()=>{const a=['site','mixed','strict'],i=(a.indexOf(state.profile)+1)%a.length;state.profile=a[i];tracks.clear();save()};
$('modelMode').onclick=async()=>{state.modelMode=state.modelMode==='fast'?'accurate':'fast';save();if(running)await loadModel()};
$('dogGuard').onclick=()=>{state.dogGuard=!state.dogGuard;save()};$('lockSetup').onclick=()=>{state.setupLocked=!state.setupLocked;save()};$('pause').onclick=()=>{state.paused=!state.paused;save()};
$('minus').onclick=()=>{state.inside=Math.max(0,state.inside-1);save()};$('plus').onclick=()=>{state.inside++;save()};$('manualIn').onclick=()=>record($('manualType').value,'IN','MANUAL');$('manualOut').onclick=()=>record($('manualType').value,'OUT','MANUAL');
$('undo').onclick=()=>{const e=state.events.shift();if(!e)return;if(e.dir==='IN'){state.inTotal=Math.max(0,state.inTotal-1);state.inside=Math.max(0,state.inside-1)}else{state.outTotal=Math.max(0,state.outTotal-1);state.inside++}save()};
$('reset').onclick=()=>{if(confirm('Reset shift counts and movement history? Gate setup stays saved.')){state.inside=0;state.inTotal=0;state.outTotal=0;state.events=[];tracks.clear();lostBank=[];eventFingerprints=[];save()}};
$('capture').onclick=()=>{if(!running||!lastDets.length)return $('hint').textContent='No detected vehicle to capture right now.';const heavy=lastDets.filter(d=>HEAVY.has(d.class)),d=(heavy.length?heavy:lastDets).sort((a,b)=>b.score-a.score)[0],[x,y,w,h]=d.bbox,pad=.12,sx=Math.max(0,x-w*pad),sy=Math.max(0,y-h*pad),sw=Math.min(canvas.width-sx,w*(1+2*pad)),sh=Math.min(canvas.height-sy,h*(1+2*pad)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(sw));c.height=Math.max(1,Math.round(sh));c.getContext('2d').drawImage(video,sx,sy,sw,sh,0,0,c.width,c.height);const label=$('manualType').value.replace(/[^a-z0-9]+/gi,'_');c.toBlob(blob=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`train_${label}_${Date.now()}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)},'image/jpeg',.9)};
$('export').onclick=()=>{const rows=[['timestamp','vehicle_type','direction','inside_after','source','track_id','detector_confidence','event_quality','quality_score'],...state.events.slice().reverse().map(e=>[e.iso,e.type,e.dir,e.inside,e.source,e.track,e.confidence,e.quality,e.qscore])],csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='site_gate_v4_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
})();